version: '3.8'

services:
  app:
    build:
      args:
        user: juancarlos
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: portal-empleado
    container_name: portal-empleado-app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
    networks:
      - portal-empleado

  nginx:
    image: nginx:alpine
    container_name: portal-empleado-nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx:/etc/nginx/conf.d
    networks:
      - portal-empleado

networks:
  portal-empleado:
    driver: bridge
